version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5172:3000"
    network_mode: host
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
